identidock:
  build: .
  ports:
    - "5000:5000"
# for docker-machine
# volumes:
#   - ./app:/app
  environment:
    - ENV=PROD
  links:
    - dnmonster
    - redis
dnmonster:
  image: amouat/dnmonster:1.0
redis:
  image: redis:3.0
proxy:
  #image: proxy:0.1
  build: ../identiproxy/
  links:
    - identidock
  ports:
    - "80:80"
  environment:
    - NGINX_HOST=104.131.117.120
    - NGINX_PROXY=http://identidock:9090
